#' Parse raw green status of species (gss) assessment data
#'
#' @description Transforms a list of raw gss assessment data from `gss_data_all()` and
#' converts to a tibble with a single row per assessment.
#' The purpose of this function is to generate a 'tidy' tibble from the raw response,
#' which we feel is easier to work with in downstream analyses.
#'
#' Due to the complexity of the taxon response, we have only included basic taxonomic
#' information to enable filtering on taxonomy or for species level.
#'
#' The more extended text fields 'justification', 'assessor_names', 'reviewer_names'
#' 'contributors', 'facilitators', 'compilers', 'url' and 'authority' have not been
#' included in the tibble returned from this function. If any of these are important
#' for your work, we would recommend fetching the data from the object created with
#' `gss_data_all()` and process according to your needs.
#'
#' @param raw_gss_data A `list()` generated by `gss_data_all()`.
#'
#' @returns Returns a tibble of green status assessment data
#' @export
#' @examples
#' \dontrun{
#' parse_gss_data(raw_gss_data)
#' }
parse_gss_data <- function(raw_gss_data) {

  purrr::map_dfr(raw_gss_data$assessments, ~dplyr::tibble(

    # From second-level taxon information, brought to start of table
    sis_id                          = .x$taxon$sis_id,
    scientific_name                 = .x$taxon$scientific_name,

    # First-level assessment information
    assessment_date                 = .x$assessment_date,
    assessment_year                 = .x$assessment_year,
    weights                         = .x$weights,
    species_recovery_category       = .x$species_recovery_category,
    species_recovery_score_best     = .x$species_recovery_score_best,
    species_recovery_score_minimum  = .x$species_recovery_score_minimum,
    species_recovery_score_maximum  = .x$species_recovery_score_maximum,
    conservation_legacy_category    = .x$conservation_legacy_category,
    conservation_legacy_best        = .x$conservation_legacy_best,
    conservation_legacy_minimum     = .x$conservation_legacy_minimum,
    conservation_legacy_maximum     = .x$conservation_legacy_maximum,
    conservation_dependence_category= .x$conservation_dependence_category,
    conservation_dependence_best    = .x$conservation_dependence_best,
    conservation_dependence_minimum = .x$conservation_dependence_minimum,
    conservation_dependence_maximum = .x$conservation_dependence_maximum,
    conservation_gain_category      = .x$conservation_gain_category,
    conservation_gain_best          = .x$conservation_gain_best,
    conservation_gain_minimum       = .x$conservation_gain_minimum,
    conservation_gain_maximum       = .x$conservation_gain_maximum,
    recovery_potential_category     = .x$recovery_potential_category,
    recovery_potential_best         = .x$recovery_potential_best,
    recovery_potential_minimum      = .x$recovery_potential_minimum,
    recovery_potential_maximum      = .x$recovery_potential_maximum,

    # Second-level taxon information
    kingdom_name                    = .x$taxon$kingdom_name,
    phylum_name                     = .x$taxon$phylum_name,
    class_name                      = .x$taxon$class_name,
    order_name                      = .x$taxon$order_name,
    family_name                     = .x$taxon$family_name,
    genus_name                      = .x$taxon$genus_name,
    species_name                    = .x$taxon$species_name,
    subpopulation_name              = .x$taxon$subpopulation_name,
    infra_name                      = .x$taxon$infra_name,
    species                         = .x$taxon$species,
    subpopulation                   = .x$taxon$subpopulation,
    infrarank                       = .x$taxon$infrarank
  ))

}
