#' Parse raw assessment data
#' @importFrom dplyr %>%
#'
#' @description Transforms a list of raw assessment data from `assessment_data()` and
#' converts to an opinionated list of unnested tibbles. The purpose of this function is to
#' generate 'tidy' tibbles from the raw response, which we feel are easier to work with
#' in downstream analyses.
#'
#' Due to the complexity of the taxon response, we have tidied the 'taxon' element, moving
#' Common Names, SSC Groups and Synonyms to named elements in the list, prepending these
#' parts of the response with `taxon_`. The same process was applied to conservation_actions_in_place,
#' which are nested under conservation_actions in the raw response. Finally, we have ordered
#' the named lists alphabetically.
#'
#' We have, for now, omitted the raw response's 'documentation' element as this is mostly
#' long paragraphs of text and HTML. If this is important for your work, we would recommend
#' fetching this from the object created with `assessment_data()` and
#' process according to your needs.
#'
#' @param raw_assessment_data A `list()` generated by `assessment_data()`.
#' @returns Returns an opinionated named list of tibbles
#' @export
#' @examples
#' \dontrun{
#' parse_assessment_data(raw_assessment_data)
#' }
parse_assessment_data <- function(raw_assessment_data) {
  # Drop unnecessary data elements
  raw_assessment_data[["documentation"]] <- NULL
  raw_assessment_data$taxon$species_taxa <- NULL
  raw_assessment_data$taxon$subpopulation_taxa <- NULL
  raw_assessment_data$taxon$infrarank_taxa <- NULL
  raw_assessment_data$taxon$authority <- NULL

  common_names <- list_to_tibble(raw_assessment_data$taxon$common_names)
  ssc_groups <- list_to_tibble(raw_assessment_data$taxon$ssc_groups)
  synonyms <- list_to_tibble(raw_assessment_data$taxon$synonyms)

  conservation_actions_in_place <- nested_list_to_tibble(
    raw_assessment_data$supplementary_info$conservation_actions_in_place
  )

  # Delete from raw response for subsequent parsing and flattening
  raw_assessment_data$taxon$common_names <- NULL
  raw_assessment_data$taxon$ssc_groups <- NULL
  raw_assessment_data$taxon$synonyms <- NULL
  raw_assessment_data$supplementary_info$conservation_actions_in_place <- NULL

  processed_list <- purrr::map(raw_assessment_data, parse_element_to_tibble)
  processed_list <- purrr::map(processed_list, flatten_tibble)

  if (nrow(processed_list$stresses) > 0) {
    processed_list$stresses <- processed_list$stresses %>%
      dplyr::distinct(description, code)
  }

  processed_list$taxon_common_names <- common_names
  processed_list$taxon_ssc_groups <- ssc_groups
  processed_list$taxon_synonyms <- synonyms
  processed_list$conservation_actions_in_place <- conservation_actions_in_place

  processed_list <- processed_list[sort(names(processed_list))]


  return(processed_list)
}
